//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JiraToolkit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JiraToolKit")]
        public string ConfigurationFolderName {
            get {
                return ((string)(this["ConfigurationFolderName"]));
            }
            set {
                this["ConfigurationFolderName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Configuration.json")]
        public string ConfigurationFile {
            get {
                return ((string)(this["ConfigurationFile"]));
            }
            set {
                this["ConfigurationFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{
  ""StayOnTop"": true,
  ""Environments"": [
    {
      ""Name"": ""My Jira"",
      ""Prefixes"": [
        ""PREFIX1"",
        ""PREFIX2"",
        ""PREFIX3""
      ],
      ""RootUrl"": ""https://Url.To.My.Jira.com/""
    },
    {
      ""Name"": ""My Jira Two"",
      ""Prefixes"": [
        ""PREFIX4"",
        ""PREFIX5"",
        ""PREFIX6""
      ],
      ""RootUrl"": ""https://Url.To.My.JiraTwo.com/""
    }
  ],
  ""Queries"": [
    {
      ""Name"": ""Query One"",
      ""Url"": ""{{param}}""
    }
  ]
}")]
        public string Configuration {
            get {
                return ((string)(this["Configuration"]));
            }
            set {
                this["Configuration"] = value;
            }
        }
    }
}
